2024-06-19 18:53:26,231 INFO    StreamThr :12345 [internal.py:wandb_internal():85] W&B internal server running at pid: 12345, started at: 2024-06-19 18:53:26.230586
2024-06-19 18:53:26,233 DEBUG   HandlerThread:12345 [handler.py:handle_request():158] handle_request: status
2024-06-19 18:53:26,256 INFO    WriterThread:12345 [datastore.py:open_for_write():87] open: /var/scratch/mdr317/thesis/wandb/run-20240619_185326-4suglk64/run-4suglk64.wandb
2024-06-19 18:53:26,257 DEBUG   SenderThread:12345 [sender.py:send():379] send: header
2024-06-19 18:53:26,271 DEBUG   SenderThread:12345 [sender.py:send():379] send: run
2024-06-19 18:53:26,562 ERROR   SenderThread:12345 [internal_api.py:execute():344] 400 response executing GraphQL.
2024-06-19 18:53:26,563 ERROR   SenderThread:12345 [internal_api.py:execute():345] {"errors":[{"message":"you may not log runs directly to your organization, please try using your team entity","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-06-19 18:53:26,563 ERROR   SenderThread:12345 [sender.py:send_run():1009] you may not log runs directly to your organization, please try using your team entity (Error 400: Bad Request)
Traceback (most recent call last):
  File "/var/scratch/mdr317/miniconda3/lib/python3.12/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/scratch/mdr317/miniconda3/lib/python3.12/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upsert_run
    response = self.gql(
               ^^^^^^^^^
  File "/var/scratch/mdr317/miniconda3/lib/python3.12/site-packages/wandb/sdk/internal/internal_api.py", line 312, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/var/scratch/mdr317/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/scratch/mdr317/miniconda3/lib/python3.12/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/scratch/mdr317/miniconda3/lib/python3.12/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/scratch/mdr317/miniconda3/lib/python3.12/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/scratch/mdr317/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/var/scratch/mdr317/miniconda3/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/scratch/mdr317/miniconda3/lib/python3.12/site-packages/wandb/sdk/internal/sender.py", line 1007, in send_run
    server_run = self._init_run(run, config_value_dict)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/scratch/mdr317/miniconda3/lib/python3.12/site-packages/wandb/sdk/internal/sender.py", line 1079, in _init_run
    server_run, inserted, server_messages = self._api.upsert_run(
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/var/scratch/mdr317/miniconda3/lib/python3.12/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: you may not log runs directly to your organization, please try using your team entity (Error 400: Bad Request)
2024-06-19 18:53:26,695 DEBUG   HandlerThread:12345 [handler.py:handle_request():158] handle_request: shutdown
2024-06-19 18:53:26,695 INFO    HandlerThread:12345 [handler.py:finish():882] shutting down handler
2024-06-19 18:53:27,271 INFO    WriterThread:12345 [datastore.py:close():296] close: /var/scratch/mdr317/thesis/wandb/run-20240619_185326-4suglk64/run-4suglk64.wandb
2024-06-19 18:53:27,571 INFO    SenderThread:12345 [sender.py:finish():1608] shutting down sender
